### ISSUE TITLE
Wheels seem to be empty

### ISSUE THREAD

**Issue by nitzanbueno** [IL-Group/FL-Studio-API-Stubs#25]
When using `pip install`, the libraries weren't installed for me.
Upon further inspection, I used `pip download` and the resulting wheel file, along with the folder in `site-packages` after installation, didn't contain any code.

This wasn't a big issue as I just built the project from source, but that requires manually running `poetry install` as when I tried building only using pip, the build failed with the following error:
```
      Traceback (most recent call last):
        File "...\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "...\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 124, in build
          self._copy_module(zip_file)
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 265, in _copy_module
          to_add = self.find_files_to_add()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\builders\builder.py", line 171, in find_files_to_add
          for include in self._module.includes:
                         ^^^^^^^^^^^^
        File "...\AppData\Local\Programs\Python\Python311\Lib\functools.py", line 1001, in __get__
          val = self.func(instance)
                ^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\builders\builder.py", line 97, in _module
          return Module(
                 ^^^^^^^
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\utils\module.py", line 75, in __init__
          PackageInclude(
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\utils\package_include.py", line 31, in __init__
          self.check_elements()
        File "...\AppData\Local\Temp\pip-build-env-z22yjqcz\overlay\Lib\site-packages\poetry\core\masonry\utils\package_include.py", line 72, in check_elements
          raise ValueError(
      ValueError: ...\FL-Studio-API-Stubs-36.1.0\build_lib\midi_controller_scripting\arrangement does not contain any element
      [end of output]
```

It seems `build_lib` wasn't created, I'm not sure if it's because I didn't have `poetry` installed before running this, or because there's a build script missing in `pyproject.toml`.

**Comment by zz-koji** [comment]
Same problem here.

**Comment by MaddyGuthridge** [comment]
Will investigate soon. Sorry I didn't spot this sooner, my notification settings for the repo were incorrect.

**Comment by MaddyGuthridge** [comment]
I believe I've identified the issue - since `build_lib` is in the project's `.gitignore`, `poetry build` excludes all files from it. Currently trying to get it to override.

**Comment by MaddyGuthridge** [comment]
Fixed it!
